# Generated by Django 3.2.25 on 2025-04-10 10:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250405_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=core.models.today_as_datetime),
        ),
    ]
